spring:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890}
    access-token-expiration: 86400000
    refresh-token-expiration: 604800000

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/construction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resources/schema.sql
#            create-source: metadata




    profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /construction

logging:
  level:
    root: INFO
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BINDER_LOG:WARN}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true







